<script lang="ts">
    import { SvelteToast } from '@zerodevx/svelte-toast';
    import { onMount } from 'svelte';
    // import SlidingLi from "./sliding-text.svelte";

    let sticky = false;

    onMount(() => {
        new SvelteToast({
            target: document.body
        });

        const containerHeight = document.body.querySelector("#container").clientHeight;
        const navHeight = document.body.querySelector("nav").clientHeight;

        const listener = document.addEventListener('scroll', (e) => {
            const offset = window.pageYOffset;
            sticky = offset > containerHeight - navHeight / 3;
        })

        return () => {
            // @ts-ignore
            document.removeEventListener('scroll', listener)
        }
    });

</script>   

<nav class={`${sticky ? 'stick': ''}`}>
    <!-- class={`${sticky ? 'swing-out-top-bck': 'swing-in-top-fwd'}`} -->
    <ul>
        <a href="#showcase">Showcase</a>
        <a href="#contact">Contact</a>
        <!-- <SlidingLi secondText={sticky}>
            <a href="#showcase" slot="first">Showcase</a>
            <button slot="second" class="active">Engineering</button>
        </SlidingLi>
        <SlidingLi secondText={sticky}>
            <a href="#contact" slot="first">Contact</a>
            <button slot="second" class="">Photography</button>
        </SlidingLi> -->
    </ul>
    
</nav>

<style>

    nav {
        position: absolute;
        bottom: 0;
        left: 0;
        width: 100%;
        padding: 15px;
        padding-right: 20px;
        color: white;
    }

    button {
        background-color: transparent;
        color: white;
        padding: 0px;
    }

    ul {
        display: flex;
        gap: 5rem;
        justify-content: right;
        list-style-type:none;
        height: 50%;
    }

    li, a {
        color: white;
    }

    .active {
        color: aqua;
    }

    .stick {
        position: sticky;
        top: 0;
        bottom: unset;
        background-color: black;
    }

    .swing-in-top-fwd{animation:swing-in-top-fwd .5s cubic-bezier(.175,.885,.32,1.275) both;
        animation-delay: 0.6s;
    }

    .swing-out-top-bck{
        animation:swing-out-top-bck .45s cubic-bezier(.6,-.28,.735,.045) both;
        height: 0;
        animation-delay: 0s;
    }


    /* ----------------------------------------------
    * Generated by Animista on 2022-7-8 13:31:21
    * Licensed under FreeBSD License.
    * See http://animista.net/license for more info. 
    * w: http://animista.net, t: @cssanimista
    * ---------------------------------------------- */

    @keyframes swing-in-top-fwd{0%{transform:rotateX(-100deg);transform-origin:top;opacity:0}100%{transform:rotateX(0deg);transform-origin:top;opacity:1}}

    @keyframes swing-out-top-bck{
        0%{transform:rotateX(0deg);
            transform-origin:top;opacity:1
        }
        100%{transform:rotateX(-100deg);transform-origin:top;opacity:0}
    }

</style>